services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '123'
      MYSQL_DATABASE: 'db_crud'
      MYSQL_ROOT_PASSWORD: '123'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: