# Generated by Django 6.0.2 on 2026-02-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='contato',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
